### ISSUE TITLE
Still Active? 

### ISSUE THREAD

**Issue by gentookid** [mjdev/WhatsQt#3]
Hey, I'd like to know if you're still developing this but perhaps not in this repo..
I've been trying to do the same, without too much detail, just opening/restoring a session, but upon loading the cookie, I've been faced with the system not opening the previously stablished web session..
I've checked that actually, as of today, the browsers do send to /wam some form encoded data
 where tok(token sent through cookie) is present..

Also I see you've created a QWebChannel and set it, but havent seen where else in your code you're using it..

Can you point me out in some direction?
Regards.-

**Comment by magnusja** [comment]
Hey there,

nope this project is not maintained anymore. The QWebChannel is used to callback from JS to C++.

I think a there are bunch of other projects like this, eg. whatsapp-nativier which are still active. Please have a look how they do it.
